### ISSUE TITLE
그래프 가로축 데이터 간격이 불규칙한 문제

### ISSUE THREAD

**Issue by JellyBrick** [despenser08/KRList-Stats#86]
![image](https://user-images.githubusercontent.com/16558115/135595705-25900228-b633-4fe4-9bb1-50a290f450d5.png)

**Comment by despenser08** [comment]
봇이 수집하는 데이터는 정상인것으로 확인되었으나, API 쪽에서 불규칙적으로 현저히 낮은 서버수를 주는 경우가 있는것으로 확인되었습니다.
봇이 길드 캐시가 되는 시간 동안 서버수가 떨어진것으로 알려주셨는데, 이 데이터는 현재 [Discussions - Delete Request](https://github.com/despenser08/KRList-Stats/discussions/categories/delete-request)에서 삭제 요청 가능합니다.

현재는 이 데이터를 감지 & 삭제하는 마땅한 기준과 대책이 없어, 수동으로 삭제하고 있다는 점 양해 부탁드립니다.
다른 의견이 있으시다면 이슈에 댓글로 남겨주시면 검토해보겠습니다.
